### ISSUE TITLE
What are some `fs`-like npm package names?

### ISSUE THREAD

**Issue by jcalfee** [piranna/fs-fuse#1]
Your choice of a good fs like module to test with would help me get this working.  I want to see how the mount will work with common linux tools like vi and echo > or >>.

**Comment by piranna** [comment]
Can you explain your question?

**Comment by jcalfee** [comment]
Just looking a simple example.  The minimum code needed to create a mount..

I noticed that many node fuse modules will crash when I try to edit files with vi for example (temp files are created and renamed).  It makes it easy to test if you have an example.

**Comment by piranna** [comment]
Ah, ok. `fs`-like modules are modules that export the Node.js `fs` API, like for example, the Node.js `fs` module itself :-) You can be able to test using it, so wherever you mount `fs-fuse` will show a copy of your system filesystem starting at `/`. Other ones that follow that API are memory-fs, webdav-fs or dropbox-fs, although probably all the functionality is not available since they doesn't fully implement the Node.js `fs` API, just only some functions.

Hope this helps :-)
