### ISSUE TITLE
How to mirror a directory?

### ISSUE THREAD

**Issue by jb33k** [piranna/fs-fuse#5]
First of all, thank you so much for creating this 🙏

I feel stupid even asking this but I can't figure out how to create a mount based on an empty directory.

I'm starting server.js with `node server.js null M:\` and it creates M: but it is a mirror of C: - how can I get it to create M: but mirror a directory like C:\tmp? I'm stuck with Windows 10.

I'm using `null` for `dev` because here is no documentation on `dev` param but it looks like it's a some sort of device option for alternative fs modules? I'm using node's fs module so I'm assuming `dev` is not required? Is there a reason why this is required (before `path` makes it so)?

**Comment by piranna** [comment]
First of all, I've didn't tested this module on Windows, I only use Linux, so I think you are alone here. Maybe that's the reason why it mirrors `C:` on `M:` instead of showing the content of your directory, or maybe it's a bug in your filesystem code... How have you tried to run it? Are you using Dokany or something else for the FUSE part?

Regarding the `dev` argument, it's needed due to how `mount` command and syscall works on Linux, if you don't need an actual block device with your filesystem, using `null` is totally ok, since it's ignored.

**Comment by fixerivan** [comment]
hi, i have the same problem on ubuntu 19.04

i run:

mkdir test
node server.js null test

ls -lh test gives the output of the / directory

i would like to change that to a specific directory instead of the /

how can i do that? thx

**Comment by piranna** [comment]
Ok, seems both of you are using the CLI without providing a `fs` option, so it's using the Node.js `fs` built-in module by default. You would need to provide it the name or path of a module that exports a function that would return a `fs`-like object, but reviewing the code I've seen I have a bug on that too since the CLI is mostly a demo and the main purpose of the module is to be used as a library, so would need to fix that first.

**Comment by piranna** [comment]
I have just fixed the CLI, now you can set the name of a module that exports a `fs`-like object or a function or class that generates them with the `-o fs=<fs>` mount option. The options given to that function or class constructor are provided with extra `-o` options. If you want a module that can export just a directory, you can use https://github.com/juliangruber/subfs.
